/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa165.deliveryservice.restclient;

import javax.swing.table.DefaultTableModel;
import pa165.deliveryservice.restclient.api.*;
import pa165.deliveryservice.restclient.listeners.*;

/**
 * REST Client GUI
 * 
 * @author John
 */
public class RestClient extends javax.swing.JFrame {
    private final PostmanClient postmanClient;
    private final CustomerClient customerClient;
    
    /**
     * Creates new form RestClient
     */
    public RestClient() {
        String hostURL = "http://localhost:8080/pa165/rest";
         postmanClient = new PostmanClient(hostURL);
         customerClient = new CustomerClient(hostURL);

        initComponents();
        
        btnShowPostmen.addActionListener(new GetAllPostmenListener(postmanClient, postmanTable));
        btnDeletePostman.addActionListener(new DeletePostmanListener(postmanClient, postmanTable));
        btnCreatePostman.addActionListener(new CreatePostmanListener(postmanClient,postmanTable, txtPostmanName, txtPostmanSurname));
        btnUpdatePostman.addActionListener(new UpdatePostmanListener(postmanClient, postmanTable, txtPostmanName, txtPostmanSurname));
    
        btnShowCustomer.addActionListener(new GetAllCustomersListener(customerClient, customerTable));
        btnDeleteCustomer.addActionListener(new DeleteCustomerListener(customerClient, customerTable));
        btnCreateCustomer.addActionListener(new CreateCustomerListener(customerClient, customerTable, txtCustomerName, txtCustomerSurname, txtCustomerCity, txtCustomerStreet, txtCustomerPostcode));
        btnUpdateCustomer.addActionListener(new UpdateCustomerListener(customerClient, customerTable, txtCustomerName, txtCustomerSurname, txtCustomerCity, txtCustomerStreet, txtCustomerPostcode));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        customerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        customerForm = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        txtCustomerSurname = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCustomerCity = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        txtCustomerStreet = new javax.swing.JTextField();
        lblPostcode = new javax.swing.JLabel();
        txtCustomerPostcode = new javax.swing.JTextField();
        btnClearCustomer = new javax.swing.JButton();
        customerButtonPanel = new javax.swing.JPanel();
        btnShowCustomer = new javax.swing.JButton();
        btnCreateCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        postmanPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        postmanTable = new javax.swing.JTable();
        postmanForm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPostmanName = new javax.swing.JTextField();
        txtPostmanSurname = new javax.swing.JTextField();
        btnClearPostman = new javax.swing.JButton();
        postmanButtonPanel = new javax.swing.JPanel();
        btnShowPostmen = new javax.swing.JButton();
        btnCreatePostman = new javax.swing.JButton();
        btnUpdatePostman = new javax.swing.JButton();
        btnDeletePostman = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delivery Sevice REST Client");
        setResizable(false);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(441, 464));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(441, 464));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Surname", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setToolTipText("");
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        customerForm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        customerForm.setLayout(new java.awt.GridBagLayout());

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        customerForm.add(lblName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 202);
        customerForm.add(txtCustomerName, gridBagConstraints);

        lblSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSurname.setText("Surname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        customerForm.add(lblSurname, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 202);
        customerForm.add(txtCustomerSurname, gridBagConstraints);

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        customerForm.add(lblCity, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 202);
        customerForm.add(txtCustomerCity, gridBagConstraints);

        lblStreet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreet.setText("Street:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        customerForm.add(lblStreet, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 202);
        customerForm.add(txtCustomerStreet, gridBagConstraints);

        lblPostcode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPostcode.setText("Postcode:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        customerForm.add(lblPostcode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 7, 202);
        customerForm.add(txtCustomerPostcode, gridBagConstraints);

        btnClearCustomer.setText("Clear form");
        btnClearCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCustomerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        customerForm.add(btnClearCustomer, gridBagConstraints);

        customerButtonPanel.setMaximumSize(new java.awt.Dimension(452, 23));
        customerButtonPanel.setMinimumSize(new java.awt.Dimension(452, 23));
        customerButtonPanel.setLayout(new java.awt.GridLayout(1, 0));

        btnShowCustomer.setText("Show customers");
        customerButtonPanel.add(btnShowCustomer);

        btnCreateCustomer.setText("Create");
        customerButtonPanel.add(btnCreateCustomer);

        btnUpdateCustomer.setText("Update selected");
        customerButtonPanel.add(btnUpdateCustomer);

        btnDeleteCustomer.setText("Delete selected");
        customerButtonPanel.add(btnDeleteCustomer);

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(customerForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(customerButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", customerPanel);

        postmanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Surname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        postmanTable.setToolTipText("");
        postmanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postmanTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(postmanTable);

        postmanForm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Postman", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        postmanForm.setLayout(new java.awt.GridBagLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        postmanForm.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Surname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        postmanForm.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 202);
        postmanForm.add(txtPostmanName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 202);
        postmanForm.add(txtPostmanSurname, gridBagConstraints);

        btnClearPostman.setText("Clear form");
        btnClearPostman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPostmanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        postmanForm.add(btnClearPostman, gridBagConstraints);

        postmanButtonPanel.setMaximumSize(new java.awt.Dimension(452, 23));
        postmanButtonPanel.setMinimumSize(new java.awt.Dimension(452, 23));
        postmanButtonPanel.setPreferredSize(new java.awt.Dimension(452, 23));
        postmanButtonPanel.setLayout(new java.awt.GridLayout(1, 0));

        btnShowPostmen.setText("Show postmen");
        btnShowPostmen.setMaximumSize(new java.awt.Dimension(65, 23));
        btnShowPostmen.setMinimumSize(new java.awt.Dimension(65, 23));
        btnShowPostmen.setPreferredSize(new java.awt.Dimension(65, 23));
        postmanButtonPanel.add(btnShowPostmen);

        btnCreatePostman.setText("Create");
        postmanButtonPanel.add(btnCreatePostman);

        btnUpdatePostman.setText("Update selected");
        postmanButtonPanel.add(btnUpdatePostman);

        btnDeletePostman.setText("Delete selected");
        postmanButtonPanel.add(btnDeletePostman);

        javax.swing.GroupLayout postmanPanelLayout = new javax.swing.GroupLayout(postmanPanel);
        postmanPanel.setLayout(postmanPanelLayout);
        postmanPanelLayout.setHorizontalGroup(
            postmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addGroup(postmanPanelLayout.createSequentialGroup()
                .addComponent(postmanForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(postmanButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        postmanPanelLayout.setVerticalGroup(
            postmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postmanPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postmanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postmanForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Postman", postmanPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
       DefaultTableModel model = (DefaultTableModel)customerTable.getModel();
       txtCustomerName.setText(model.getValueAt(customerTable.getSelectedRow(), 1).toString());
       txtCustomerSurname.setText(model.getValueAt(customerTable.getSelectedRow(), 2).toString());
       String address = model.getValueAt(customerTable.getSelectedRow(), 3).toString();
       String parsedAddress[] = address.split(",",3);
       txtCustomerCity.setText(parsedAddress[0]);
       txtCustomerStreet.setText(parsedAddress[1]);
       txtCustomerPostcode.setText(parsedAddress[2]);
    }//GEN-LAST:event_customerTableMouseClicked

    private void postmanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postmanTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)postmanTable.getModel();
        txtPostmanName.setText(model.getValueAt(postmanTable.getSelectedRow(), 1).toString());
        txtPostmanSurname.setText(model.getValueAt(postmanTable.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_postmanTableMouseClicked

    private void btnClearCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCustomerActionPerformed
        txtCustomerName.setText(null);
        txtCustomerSurname.setText(null);
        txtCustomerCity.setText(null);
        txtCustomerStreet.setText(null);
        txtCustomerPostcode.setText(null);        
    }//GEN-LAST:event_btnClearCustomerActionPerformed

    private void btnClearPostmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPostmanActionPerformed
        txtPostmanName.setText(null);
        txtPostmanSurname.setText(null);
    }//GEN-LAST:event_btnClearPostmanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCustomer;
    private javax.swing.JButton btnClearPostman;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnCreatePostman;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnDeletePostman;
    private javax.swing.JButton btnShowCustomer;
    private javax.swing.JButton btnShowPostmen;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnUpdatePostman;
    private javax.swing.JPanel customerButtonPanel;
    private javax.swing.JPanel customerForm;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPostcode;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JPanel postmanButtonPanel;
    private javax.swing.JPanel postmanForm;
    private javax.swing.JPanel postmanPanel;
    private javax.swing.JTable postmanTable;
    private javax.swing.JTextField txtCustomerCity;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPostcode;
    private javax.swing.JTextField txtCustomerStreet;
    private javax.swing.JTextField txtCustomerSurname;
    private javax.swing.JTextField txtPostmanName;
    private javax.swing.JTextField txtPostmanSurname;
    // End of variables declaration//GEN-END:variables
}
